//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystemWPFApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int LogId { get; set; }
        public int EmployeeId { get; set; }
        public int LeaseId { get; set; }
        public int TenantId { get; set; }
        public int MallId { get; set; }
        public int PavilionId { get; set; }
        public int MallStatusId { get; set; }
        public System.DateTime LeaseStart { get; set; }
        public System.DateTime LeaseEnd { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Malls Malls { get; set; }
        public virtual MallStatuses MallStatuses { get; set; }
        public virtual Pavilions Pavilions { get; set; }
        public virtual PavilionsLease PavilionsLease { get; set; }
        public virtual Tenants Tenants { get; set; }
    }
}
