//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystemWPFApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KingITEntities : DbContext
    {
        public KingITEntities()
            : base("name=KingITEntities")
        {
        }

        private static KingITEntities _context;

        public static KingITEntities GetContext()
        {
            if (_context == null)
            {
                _context = new KingITEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Malls> Malls { get; set; }
        public virtual DbSet<MallStatuses> MallStatuses { get; set; }
        public virtual DbSet<Pavilions> Pavilions { get; set; }
        public virtual DbSet<PavilionsLease> PavilionsLease { get; set; }
        public virtual DbSet<PavilionsStatuses> PavilionsStatuses { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tenants> Tenants { get; set; }
        public virtual DbSet<log> log { get; set; }
    
        public virtual int RentPavilion(Nullable<int> pavilionId, Nullable<System.DateTime> leaseStart, Nullable<System.DateTime> leaseEnd, Nullable<int> tenantId, Nullable<int> empId)
        {
            var pavilionIdParameter = pavilionId.HasValue ?
                new ObjectParameter("PavilionId", pavilionId) :
                new ObjectParameter("PavilionId", typeof(int));
    
            var leaseStartParameter = leaseStart.HasValue ?
                new ObjectParameter("LeaseStart", leaseStart) :
                new ObjectParameter("LeaseStart", typeof(System.DateTime));
    
            var leaseEndParameter = leaseEnd.HasValue ?
                new ObjectParameter("LeaseEnd", leaseEnd) :
                new ObjectParameter("LeaseEnd", typeof(System.DateTime));
    
            var tenantIdParameter = tenantId.HasValue ?
                new ObjectParameter("TenantId", tenantId) :
                new ObjectParameter("TenantId", typeof(int));
    
            var empIdParameter = empId.HasValue ?
                new ObjectParameter("EmpId", empId) :
                new ObjectParameter("EmpId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RentPavilion", pavilionIdParameter, leaseStartParameter, leaseEndParameter, tenantIdParameter, empIdParameter);
        }
    
        public virtual int RescheduleLease()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RescheduleLease");
        }
    }
}
