//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManagementSystemWPFApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilions()
        {
            this.PavilionsLease = new HashSet<PavilionsLease>();
            this.log = new HashSet<log>();
        }
    
        public int PavilionId { get; set; }
        public string PavilionNumber { get; set; }
        public int MallId { get; set; }
        public int LevelNumber { get; set; }
        public int PavilionStatusId { get; set; }
        public double Area { get; set; }
        public double SquareMeterCost { get; set; }
        public double ValueAddedFactor { get; set; }
    
        public virtual Malls Malls { get; set; }
        public virtual PavilionsStatuses PavilionsStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PavilionsLease> PavilionsLease { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<log> log { get; set; }
    }
}
